### ISSUE TITLE
Labeled as WIP for a while, what needs to be done?

### ISSUE THREAD

**Issue by califrench** [vapor-community/markdown-provider#1]
Hey there, I'm excited to be able to use this module as part of Vapor. It's still labelled as a WIP on the README.md.
Let's get a list of issues going so contributors know where to start working.
Biggest thing I see right now for obvious reasons is `markdownToHTML` needs to be implemented.
I'd be happy to contribute!

**Comment by tanner0101** [comment]
Hi @califrench, it looks like @czechboy0 created this package a while back. I'm not quite sure what is left to be implemented, but updating the Package.swift to the latest Vapor would be a good place to start

```swift
import PackageDescription

let package = Package(
    name: "VaporMarkdown",
    targets: [
    	Target(name: "vapor-markdown-example", dependencies: ["vapor-markdown"])
    ],
    dependencies: [
    	.Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1), // change to vapor 1.x
    	.Package(url: "https://github.com/czechboy0/cmark.swift.git", majorVersion: 0, minor: 1)
    ]
)
```

Also feel free to join http://vapor.team if you want to chat with the team directly.

**Comment by 0xTim** [comment]
@califrench I've forked this here https://github.com/brokenhandsio/LeafMarkdown

Works with CommonMark, soon to be Github Flavoured Markdown. Once that's done I'll talk to @tanner0101 about getting it merged back in upstream

**Comment by califrench** [comment]
Hi @tanner0101 , I'm actually already on the Vapor slack 😄 
@0xTim I'll take a look at your repo. Are you looking for contributors?

I'll leave this issue open till [LeafMarkdown](https://github.com/brokenhandsio/LeafMarkdown) is merged upstream....

**Comment by 0xTim** [comment]
@califrench Yeah always happy to accept PRs for any of the Open Source stuff I've got in Broken Hands! Though I think LeafMarkdown is pretty stable, other than a Vapor 2 update. It's the underlying library that does all the work and that is all done with cmark

**Comment by califrench** [comment]
So I see that there are basically 2 packages at this point:
- [vapor/markdown](https://github.com/vapor/markdown) which is the one from @czechboy0 
- [brokenhandsio/LeafMarkdown](https://github.com/brokenhandsio/LeafMarkdown) which is the one from @0xTim 

I added LeafMarkdown to my repo and am pretty happy with it so far. But are there any differences with `vapor/markdown`?

Also since `vapor/markdown` is available, maybe this repo (`vapor/markdown-provider`) should be killed off?

**Comment by 0xTim** [comment]
@califrench Vapor/Markdown is the wrapper around `cmark` to make it play nice in Swift. The provider is the easy way of adding them to your project. LeafMarkdown and the Markdown Provider are the same thing, but if you look at the dependencies of LeafMarkdown it also relies on the markdown package (though a fork of it)

**Comment by 0xTim** [comment]
@califrench the latest release to LeafMarkdown (https://github.com/brokenhandsio/LeafMarkdown/releases/tag/0.3.0-beta.2), and the updates to SwiftMarkdown (my fork of vapor/markdown) basically has everything in it that I'm planning on adding. Once Vapor 2 is released I'll create a new release and merge back into upstream. I'll keep on top of any changes to cmark-gfm to make sure upstream changes in that are pulled in.

**Comment by 0xTim** [comment]
Closing this issue as I've merged all of the work upstream! Release can be found here https://github.com/vapor-community/markdown-provider/releases/tag/1.0.0
